name: manajemen_museum
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  csv: ^6.0.0
  dart_console: ^4.1.1
  interact_cli: ^2.4.0
  intl: ^0.19.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
